### PR TITLE
Allow to customize the base logger when using textual logging

### PR DESCRIPTION
**Pull request by gmaz42**
## Which problem is this PR solving?

It is currently not possible to specify a custom base logger, for example with specific flags (e.g. no timestamp). All created loggers have these flags: `log.LstdFlags|log.Lmicroseconds|log.LUTC|log.Lmsgprefix`.

## Short description of the changes

Allow specifying a stdlib `*log.Logger` which in turn can use any custom flag

### CODE REVIEW

**Review by mantzas — CHANGES_REQUESTED** [review]
Hey, can you add a test?

**Comment by mantzas** [comment]
@gmaz42 is io.Writer not enough? It is the most simple/generic thing.

**Comment by gmaz42** [comment]
@mantzas sure; note that I have changed the method signature to specify `flags` instead, I think it is better so that format stays consistent.

**Comment by gmaz42** [comment]
> is io.Writer not enough? It is the most simple/generic thing.

The problem is with the flags: in some cases it is best to not print the initial timestamp because it is printed already by another calling system

**Comment by mantzas** [comment]
> > is io.Writer not enough? It is the most simple/generic thing.
> 
> The problem is with the flags: in some cases it is best to not print the initial timestamp because it is printed already by another calling system

But the 2 logs should be separate ones and the timestamps will also not be the same. I most probably miss the context but do not worry.

**Comment by gmaz42** [comment]
> But the 2 logs should be separate ones and the timestamps will also not be the same. I most probably miss the context but do not worry.

It is a situation where we have Python calling the Go process:
```
[2021-09-19 10:11:39,451] {Kafka_Publisher.py:43} INFO - b'{"lvl":"fatal","host":"0de9dbe45553","srv":"notebooks","ver":"4178698","time":"2021-09-19T10:11:39.451166085Z","src":"cmd/main.go:103","msg":"error: rpc error: code = Unavailable desc = Service Unavailable: HTTP status code 503; transport: received the unexpected content-type \\"text/plain; charset=utf-8\\""}'
```

The Python one cannot be removed because otherwise the Python errors would be deprived of a timestamp.

**Comment by mantzas** [comment]
> > But the 2 logs should be separate ones and the timestamps will also not be the same. I most probably miss the context but do not worry.
> 
> It is a situation where we have Python calling the Go process:
> 
> ```
> [2021-09-19 10:11:39,451] {Kafka_Publisher.py:43} INFO - b'{"lvl":"fatal","host":"0de9dbe45553","srv":"notebooks","ver":"4178698","time":"2021-09-19T10:11:39.451166085Z","src":"cmd/main.go:103","msg":"error: rpc error: code = Unavailable desc = Service Unavailable: HTTP status code 503; transport: received the unexpected content-type \\"text/plain; charset=utf-8\\""}'
> ```
> 
> The Python one cannot be removed because otherwise the Python errors would be deprived of a timestamp.

That makes sense!

**Review by drakos74 — APPROVED** [review]

**Review by mantzas — APPROVED** [review]

**Pull request merged**
