### PR TITLE
#277 - Fix port conflict for sixth and seventh examples

### LINKED ISSUE #277: Cannot start 'seventh' and 'sixth' example together
## Is your feature request related to a problem? Please describe
The sixth and seventh example are both using port 50006 for a GRPC and an HTTP endpoint respectively. That means that they cannot be launched together.

## Is this a bug? Please provide steps to reproduce, a failing test etc.

Change into the patron/examples directory and try to run 
```go
$ go run sixth/main.go
$ go run seventh/main.go 
{"lvl":"debug","host":"Paschalis-Tsilias.local","srv":"seventh","ver":"1.0.0","time":"2020-10-21T17:00:00.381556+03:00","src":"patron/service.go:121","msg":"closing tracer"}
2020/10/21 17:00:00 failed to create and run service listen tcp :50006: bind: address already in use

$ go run seventh/main.go 
$ go run sixth/main.go
{"lvl":"fatal","host":"Paschalis-Tsilias.local","srv":"sixth","ver":"1.0.0","time":"2020-10-21T17:00:09.284834+03:00","src":"runtime/proc.go:204","msg":"failed to create and run service: failed to listen: listen tcp :50006: bind: address already in use\n"}
```

## Describe the solution

Use a different port for the 'seventh' example which showcases the server-side caching. This change should be reflected to the 'first' example and the `DoTimingRequest` function.

## Additional context
None, for now.

### PR DESCRIPTION
**Pull request by bhiravabhatla**
Signed-off-by: santosh <bsantosh@thoughtworks.com>

## Which problem is this PR solving?
Resolves #277

## Short description of the changes
Change port for seventh example to 50007 to avoid conflict with sixth example. Also change the port in DoTimingRequest function of 1st example which uses service exposed by 7th example.

### CODE REVIEW

**Review by mantzas — DISMISSED** [review]

**Review by tpaschalis — DISMISSED** [review]
Hello Santosh, and thanks for opening your first PR in Patron! 🎉 This looks good to me, pretty straightforward.

By the way, if you've had the time to read through some of the examples while fixing this issue, any comments are welcome!

**Comment by bhiravabhatla** [comment]
Thank you. Yeah, I guess, we would need a little more documentation around it. I am happy to help with it, any suggestions around it?

**Comment by tpaschalis** [comment]
We're currently in the process of adding new documentation, tracked in issue #272. 

If you have any comments regarding the readability of the examples, or ideas for new ones, we'd love to hear them and take them into consideration for the docs revamp.

**Review by drakos74 — DISMISSED** [review]

**Comment by mantzas** [comment]
@bhiravabhatla any reason fr this to be closed?

**Comment by bhiravabhatla** [comment]
Sorry closed this by mistake. my bad :(

**Comment by bhiravabhatla** [comment]
I pushed a commit fixing the bug I raised yesterday. Let me revert that and create another PR for the same. Sorry fo the inconvinience

**Comment by bhiravabhatla** [comment]
Reverted the commit made by mistake. Sorry, I guess you would have approve the PR again. @mantzas @tpaschalis @drakos74 , my bad.

**Review by tpaschalis — APPROVED** [review]

**Comment by tpaschalis** [comment]
Hey @bhiravabhatla, how are you doing? Was this closed by accident?

**Comment by bhiravabhatla** [comment]
@tpaschalis  - Yes, my bad - Closed it by mistake.

**Comment by tpaschalis** [comment]
Feel free to re-open and rebase with master!

**Comment by bhiravabhatla** [comment]
@tpaschalis  - will do that, had to force push my master branch as it was out of sync and I was working on some other bug and needed a clean master to branch from. I ll raise a new PR for this. sorry for the inconvenience caused.

**Comment by bhiravabhatla** [comment]
> Feel free to re-open and rebase with master!

Raised https://github.com/beatlabs/patron/pull/290

**Comment by tpaschalis** [comment]
> @tpaschalis - will do that, had to force push my master branch as it was out of sync and I was working on some other bug and needed a clean master to branch from. I ll raise a new PR for this. sorry for the inconvenience caused.

No worries ^^ the new PR is already merged!

**Pull request closed without merging**
