### PR TITLE
Correctly skip log stacktrace entries for 'src'

### PR DESCRIPTION
**Pull request by gmaz42**
## Which problem is this PR solving?

When using `examples/http/main.go` for reference, the initial log is:
```
{"lvl":"info","host":"local","srv":"httpHandler","ver":"1.0.0","time":"2021-09-01T08:02:18.551267183+02:00","src":"log/logger.go:123","msg":"debug logging disabled"}
{"lvl":"info","host":"local","srv":"httpHandler","ver":"1.0.0","time":"2021-09-01T08:02:18.551636504+02:00","src":"log/logger.go:123","msg":"debug logging disabled"}
{"lvl":"info","host":"local","srv":"httpHandler","ver":"1.0.0","time":"2021-09-01T08:02:18.552722376+02:00","src":"runtime/proc.go:225","msg":"listening on port 5000"}
{"lvl":"info","host":"local","srv":"httpHandler","ver":"1.0.0","time":"2021-09-01T08:02:18.553375775+02:00","src":"example/main.go:80","msg":"service httpHandler started"}
```

Notice `"src":"runtime/proc.go:225"` for the entry `listening on port 5000`.

## Short description of the changes

When changing the skip number for the printf logger from 7 to 6 we have instead:
```
{"lvl":"info","host":"local","srv":"httpHandler","ver":"1.0.0","time":"2021-09-01T08:03:21.247921559+02:00","src":"trace/trace.go:128","msg":"debug logging disabled"}
{"lvl":"info","host":"local","srv":"httpHandler","ver":"1.0.0","time":"2021-09-01T08:03:21.248245903+02:00","src":"trace/trace.go:128","msg":"debug logging disabled"}
{"lvl":"info","host":"local","srv":"httpHandler","ver":"1.0.0","time":"2021-09-01T08:03:21.249253469+02:00","src":"example/main.go:73","msg":"listening on port 5000"}
{"lvl":"info","host":"local","srv":"httpHandler","ver":"1.0.0","time":"2021-09-01T08:03:21.25011907+02:00","src":"patron/service.go:463","msg":"service httpHandler started"}
```

Notice `"src":"example/main.go:73"` for the entry `listening on port 5000`.

This PR contains a commit with an additional bugfix (missing `set -e`) and improvement (`exec`, saves 1 process) for the scripts under `examples/` but that can be dropped from this PR.

### CODE REVIEW

**Comment by mantzas** [comment]
@gmaz42 Hey, thanks for the PR. After some back and forth we managed to make logging work for the services that are deployed which have though side-effects on some use cases. Could it be that with this change we might fix the example but break any service in prod?

**Comment by gmaz42** [comment]
> Could it be that with this change we might fix the example but break any service in prod?

I tested it with Sonar and fraud-prevention and it worked with the log lines originated from their `main.go`; however now that you mention it I think the behavior for log lines started in goroutines should also be verified :thinking: I will check that.

It should work because it scans the file paths, but let's see.

**Comment by mantzas** [comment]
> > Could it be that with this change we might fix the example but break any service in prod?
> 
> I tested it with Sonar and fraud-prevention and it worked with the log lines originated from their `main.go`; however now that you mention it I think the behavior for log lines started in goroutines should also be verified  I will check that.
> 
> It should work because it scans the file paths, but let's see.

TBH We have removed the source logging from the text logger because of a lot of inconsistencies. I was thinking also to remove it eventually from the JSON logger. Let's see.

**Comment by gmaz42** [comment]
> TBH We have removed the source logging from the text logger because of a lot of inconsistencies. I was thinking also to remove it eventually from the JSON logger. Let's see.

In current `master` it always logs an useless entry in the services we have, that is why I was moved to make this PR; I guess we could make it optional and disabled by default.

Just checked with a microservice running and it reports correct `src`.

**Review by mantzas — APPROVED** [review]

**Review by teivah — APPROVED** [review]

**Review by mantzas — APPROVED** [review]

**Pull request merged**
